import Header from "@/components/header"
import Footer from "@/components/footer"

export const metadata = {
  title: 'JOJOS',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="follow-margin">
          <Header />
          {children}
        </div>
        <Footer />
      </body>
    </html>
  )
}
